[package]
name = "fatplow"
version = "1.0.2"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["derive"] }
clap = { version = "4.5.52", features = ["derive"] }
itertools = "0.14.0"
